#!/usr/bin/env bash
#! Script to install Nginx in a server
apt-get -y update
apt-get install -y nginx
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Holberton School" > /var/www/html/index.html
service nginx restart
