#!/usr/bin/env bash
#! Script to install Nginx in a server
apt-get -y update
apt-get install -y nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx restart
