#!/usr/bin/env bash
# redirect with 301

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
