#!/usr/bin/env bash
#! Script to install Nginx in a server
sudo apt-get update
sudo apt-get -y install nginx
cd /etc/nginx/sites-available
sudo sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' default
sudo service nginx start
