#!/usr/bin/env bash
# redirect with 301

sudo apt-get update
sudo apt-get -y install nginx
cd /etc/nginx/sites-available
new_value="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_value/" default
sudo service nginx start
