#!/usr/bin/env bash
#! Script to install Nginx in a server
apt-get -y update
apt-get install -y nginx
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Holberton School" > /var/www/html/index.html
service nginx restart
#!/usr/bin/env bash
# redirect with 301

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-enabled/default 
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
