#!/usr/bin/env bash
#! Script to install Nginx in a server
apt-get -y update
apt-get install -y nginx
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Holberton School" > /var/www/html/index.html
service nginx restart
#!/usr/bin/env bash
# redirect with 301

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-enabled/default 
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
#!/usr/bin/env bash
# redirect with 301

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Ceci n'est pas une page" > /var/www/html/404_error.html
sudo sed -i "52i \\\terror_page 404 \/404_error.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default 
sudo service nginx restart
