#!/usr/bin/env bash
# redirect with 301

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404_error.html
sudo sed -i "52i \\\terror_page 404 \/404_error.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default 
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-enabled/default
sudo sed -i "17i \\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
