#!/usr/bin/env bash
# Haproxy  INSTALLATION AND CONFIGURATION
sudo apt-get -y update

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get -y update
sudo apt-get install -y haproxy=1.7.\*


sudo sed -i "5i ENABLED=1" /etc/default/haproxy
sudo service haproxy start

echo -e "
backend web-backend\n
\tbalance roundrobin \n\
\tserver 730-web-01 35.237.185.239 check \n\
\tserver 730-web-02 35.196.231.114 check" > backend

echo -e "
frontend http \n\
\tbind *:80 \n\
\tmode http \n\
\tdefault_backend web-backend " > frontend

cat /etc/haproxy/haproxy.cfg backend frontend > example
sudo mv example /etc/haproxy/haproxy.cfg

sudo rm frontend backend
