#!/usr/bin/env bash
# Haproxy  INSTALLATION AND CONFIGURATION
sudo apt-get update

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get update
sudo apt-get install -y haproxy=1.7.\*

echo -e "

frontend http\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web-backend

backend web-backend\n
\tbalance roundrobin\n\
\tserver 730-web-01 35.237.185.239:80 check\n\
\tserver 730-web-02 35.196.231.114:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy reload
