#!/usr/bin/env bash
# Script to install mysql
echo 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7-dmr' | sudo tee -a /etc/apt/sources.list

sudo apt-get update
sudo apt-get install mysql-server-5.7

echo "**** Check the mysql --version ****"
mysql --version
