#!/usr/bin/env bash
# This script displaying process in a user-oriented format
echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me?!"' 2
trap 'sudo kill -15 "$(cat /var/run/holbertonscript.pid)"; rm /var/run/holbertonscript.pid' 15
trap 'sudo kill -3 "$(cat /var/run/holbertonscript.pid)"; rm /var/run/holbertonscript.pid' 3

while :
do
    echo "To infinity and beyond"
    sleep 2
done
