#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
HOLBI="Holberton School"
COUNT=0
while (( COUNT < 10 ))
do
    echo "$HOLBI"
    if [ "$COUNT" -eq "8" ]
    then
	echo "Hi"
    fi
    (( COUNT++ ))
done
