#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
HOLBI="Holberton School"
COUNT=0
while (( COUNT < 10 ))
do
    if [ "$COUNT" -eq "3" ]
    then
	echo "bad luck"
    elif [ "$COUNT" -eq "7" ]
    then
	echo "good luck"
    else
	echo "$HOLBI"
    fi
    (( COUNT++ ))
done
