#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
HOUR=0
MINUTES=1
while [ "$HOUR" -lt "13" ]
do
    echo "Hour: $HOUR"
    while [ "$MINUTES" -lt "60" ]
    do
	echo "$MINUTES"
	(( MINUTES++ ))
    done
    MINUTES=1
    (( HOUR++ ))
done
