#!/usr/bin/env bash
#File to change the value of the ip in the localhost
#sed -i "s/127.0.0.1/127.0.0.2/g" /etc/hosts
#sed '/facebook/dg' /etc/hosts
#sed "/127.0.0.1 localhost/ag '8.8.8.8 facebook./com'" /etc/hosts
#sed -i "s/32.342.24/8.8.8.8/g" /etc/hosts
echo -e "127.0.0.2 localhost\n8.8.8.8 facebook.com" > /etc/hosts
